// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------------- //
// StepperSpeedController //
// ---------------------- //

#define StepperSpeedController_wrap_target 0
#define StepperSpeedController_wrap 7
#define StepperSpeedController_pio_version 0

static const uint16_t StepperSpeedController_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6050, //  1: out    y, 16                      
    0x6030, //  2: out    x, 16                      
    0xe001, //  3: set    pins, 1                    
    0x0044, //  4: jmp    x--, 4                     
    0xe000, //  5: set    pins, 0                    
    0xa022, //  6: mov    x, y                       
    0x0047, //  7: jmp    x--, 7                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program StepperSpeedController_program = {
    .instructions = StepperSpeedController_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = StepperSpeedController_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config StepperSpeedController_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + StepperSpeedController_wrap_target, offset + StepperSpeedController_wrap);
    return c;
}
#endif

